// Liste ISO complète des pays (ISO 3166-1 alpha-2) avec noms FR/EN
// Ville = champ texte libre dans les formulaires
export interface Country {
  code: string;
  fr: string;
  en: string;
  cities: string[]; // Kept for backward compat, empty for free text
}

export const COUNTRIES: Country[] = [
  { code: "AF", fr: "Afghanistan", en: "Afghanistan", cities: [] },
  { code: "ZA", fr: "Afrique du Sud", en: "South Africa", cities: [] },
  { code: "AL", fr: "Albanie", en: "Albania", cities: [] },
  { code: "DZ", fr: "Algérie", en: "Algeria", cities: [] },
  { code: "DE", fr: "Allemagne", en: "Germany", cities: [] },
  { code: "AD", fr: "Andorre", en: "Andorra", cities: [] },
  { code: "AO", fr: "Angola", en: "Angola", cities: [] },
  { code: "AI", fr: "Anguilla", en: "Anguilla", cities: [] },
  { code: "AQ", fr: "Antarctique", en: "Antarctica", cities: [] },
  { code: "AG", fr: "Antigua-et-Barbuda", en: "Antigua and Barbuda", cities: [] },
  { code: "SA", fr: "Arabie saoudite", en: "Saudi Arabia", cities: [] },
  { code: "AR", fr: "Argentine", en: "Argentina", cities: [] },
  { code: "AM", fr: "Arménie", en: "Armenia", cities: [] },
  { code: "AW", fr: "Aruba", en: "Aruba", cities: [] },
  { code: "AU", fr: "Australie", en: "Australia", cities: [] },
  { code: "AT", fr: "Autriche", en: "Austria", cities: [] },
  { code: "AZ", fr: "Azerbaïdjan", en: "Azerbaijan", cities: [] },
  { code: "BS", fr: "Bahamas", en: "Bahamas", cities: [] },
  { code: "BH", fr: "Bahreïn", en: "Bahrain", cities: [] },
  { code: "BD", fr: "Bangladesh", en: "Bangladesh", cities: [] },
  { code: "BB", fr: "Barbade", en: "Barbados", cities: [] },
  { code: "BE", fr: "Belgique", en: "Belgium", cities: [] },
  { code: "BZ", fr: "Belize", en: "Belize", cities: [] },
  { code: "BJ", fr: "Bénin", en: "Benin", cities: [] },
  { code: "BM", fr: "Bermudes", en: "Bermuda", cities: [] },
  { code: "BT", fr: "Bhoutan", en: "Bhutan", cities: [] },
  { code: "BY", fr: "Biélorussie", en: "Belarus", cities: [] },
  { code: "BO", fr: "Bolivie", en: "Bolivia", cities: [] },
  { code: "BA", fr: "Bosnie-Herzégovine", en: "Bosnia and Herzegovina", cities: [] },
  { code: "BW", fr: "Botswana", en: "Botswana", cities: [] },
  { code: "BR", fr: "Brésil", en: "Brazil", cities: [] },
  { code: "BN", fr: "Brunei", en: "Brunei", cities: [] },
  { code: "BG", fr: "Bulgarie", en: "Bulgaria", cities: [] },
  { code: "BF", fr: "Burkina Faso", en: "Burkina Faso", cities: [] },
  { code: "BI", fr: "Burundi", en: "Burundi", cities: [] },
  { code: "KH", fr: "Cambodge", en: "Cambodia", cities: [] },
  { code: "CM", fr: "Cameroun", en: "Cameroon", cities: [] },
  { code: "CA", fr: "Canada", en: "Canada", cities: [] },
  { code: "CV", fr: "Cap-Vert", en: "Cape Verde", cities: [] },
  { code: "CL", fr: "Chili", en: "Chile", cities: [] },
  { code: "CN", fr: "Chine", en: "China", cities: [] },
  { code: "CY", fr: "Chypre", en: "Cyprus", cities: [] },
  { code: "CO", fr: "Colombie", en: "Colombia", cities: [] },
  { code: "KM", fr: "Comores", en: "Comoros", cities: [] },
  { code: "CG", fr: "Congo", en: "Congo", cities: [] },
  { code: "CD", fr: "Congo (RDC)", en: "Congo (DRC)", cities: [] },
  { code: "KR", fr: "Corée du Sud", en: "South Korea", cities: [] },
  { code: "KP", fr: "Corée du Nord", en: "North Korea", cities: [] },
  { code: "CR", fr: "Costa Rica", en: "Costa Rica", cities: [] },
  { code: "CI", fr: "Côte d'Ivoire", en: "Ivory Coast", cities: [] },
  { code: "HR", fr: "Croatie", en: "Croatia", cities: [] },
  { code: "CU", fr: "Cuba", en: "Cuba", cities: [] },
  { code: "CW", fr: "Curaçao", en: "Curaçao", cities: [] },
  { code: "DK", fr: "Danemark", en: "Denmark", cities: [] },
  { code: "DJ", fr: "Djibouti", en: "Djibouti", cities: [] },
  { code: "DM", fr: "Dominique", en: "Dominica", cities: [] },
  { code: "EG", fr: "Égypte", en: "Egypt", cities: [] },
  { code: "SV", fr: "Salvador", en: "El Salvador", cities: [] },
  { code: "AE", fr: "Émirats arabes unis", en: "United Arab Emirates", cities: [] },
  { code: "EC", fr: "Équateur", en: "Ecuador", cities: [] },
  { code: "ER", fr: "Érythrée", en: "Eritrea", cities: [] },
  { code: "ES", fr: "Espagne", en: "Spain", cities: [] },
  { code: "EE", fr: "Estonie", en: "Estonia", cities: [] },
  { code: "US", fr: "États-Unis", en: "United States", cities: [] },
  { code: "ET", fr: "Éthiopie", en: "Ethiopia", cities: [] },
  { code: "FJ", fr: "Fidji", en: "Fiji", cities: [] },
  { code: "FI", fr: "Finlande", en: "Finland", cities: [] },
  { code: "FR", fr: "France", en: "France", cities: [] },
  { code: "GA", fr: "Gabon", en: "Gabon", cities: [] },
  { code: "GM", fr: "Gambie", en: "Gambia", cities: [] },
  { code: "GE", fr: "Géorgie", en: "Georgia", cities: [] },
  { code: "GH", fr: "Ghana", en: "Ghana", cities: [] },
  { code: "GI", fr: "Gibraltar", en: "Gibraltar", cities: [] },
  { code: "GR", fr: "Grèce", en: "Greece", cities: [] },
  { code: "GD", fr: "Grenade", en: "Grenada", cities: [] },
  { code: "GL", fr: "Groenland", en: "Greenland", cities: [] },
  { code: "GP", fr: "Guadeloupe", en: "Guadeloupe", cities: [] },
  { code: "GU", fr: "Guam", en: "Guam", cities: [] },
  { code: "GT", fr: "Guatemala", en: "Guatemala", cities: [] },
  { code: "GG", fr: "Guernesey", en: "Guernsey", cities: [] },
  { code: "GN", fr: "Guinée", en: "Guinea", cities: [] },
  { code: "GQ", fr: "Guinée équatoriale", en: "Equatorial Guinea", cities: [] },
  { code: "GW", fr: "Guinée-Bissau", en: "Guinea-Bissau", cities: [] },
  { code: "GY", fr: "Guyana", en: "Guyana", cities: [] },
  { code: "GF", fr: "Guyane", en: "French Guiana", cities: [] },
  { code: "HT", fr: "Haïti", en: "Haiti", cities: [] },
  { code: "HN", fr: "Honduras", en: "Honduras", cities: [] },
  { code: "HK", fr: "Hong Kong", en: "Hong Kong", cities: [] },
  { code: "HU", fr: "Hongrie", en: "Hungary", cities: [] },
  { code: "IM", fr: "Île de Man", en: "Isle of Man", cities: [] },
  { code: "KY", fr: "Îles Caïmans", en: "Cayman Islands", cities: [] },
  { code: "FO", fr: "Îles Féroé", en: "Faroe Islands", cities: [] },
  { code: "MV", fr: "Maldives", en: "Maldives", cities: [] },
  { code: "MP", fr: "Îles Mariannes du Nord", en: "Northern Mariana Islands", cities: [] },
  { code: "MH", fr: "Îles Marshall", en: "Marshall Islands", cities: [] },
  { code: "SB", fr: "Îles Salomon", en: "Solomon Islands", cities: [] },
  { code: "VG", fr: "Îles Vierges britanniques", en: "British Virgin Islands", cities: [] },
  { code: "VI", fr: "Îles Vierges des États-Unis", en: "US Virgin Islands", cities: [] },
  { code: "IN", fr: "Inde", en: "India", cities: [] },
  { code: "ID", fr: "Indonésie", en: "Indonesia", cities: [] },
  { code: "IQ", fr: "Irak", en: "Iraq", cities: [] },
  { code: "IR", fr: "Iran", en: "Iran", cities: [] },
  { code: "IE", fr: "Irlande", en: "Ireland", cities: [] },
  { code: "IS", fr: "Islande", en: "Iceland", cities: [] },
  { code: "IL", fr: "Israël", en: "Israel", cities: [] },
  { code: "IT", fr: "Italie", en: "Italy", cities: [] },
  { code: "JM", fr: "Jamaïque", en: "Jamaica", cities: [] },
  { code: "JP", fr: "Japon", en: "Japan", cities: [] },
  { code: "JE", fr: "Jersey", en: "Jersey", cities: [] },
  { code: "JO", fr: "Jordanie", en: "Jordan", cities: [] },
  { code: "KZ", fr: "Kazakhstan", en: "Kazakhstan", cities: [] },
  { code: "KE", fr: "Kenya", en: "Kenya", cities: [] },
  { code: "KG", fr: "Kirghizistan", en: "Kyrgyzstan", cities: [] },
  { code: "KI", fr: "Kiribati", en: "Kiribati", cities: [] },
  { code: "KW", fr: "Koweït", en: "Kuwait", cities: [] },
  { code: "LA", fr: "Laos", en: "Laos", cities: [] },
  { code: "LS", fr: "Lesotho", en: "Lesotho", cities: [] },
  { code: "LV", fr: "Lettonie", en: "Latvia", cities: [] },
  { code: "LB", fr: "Liban", en: "Lebanon", cities: [] },
  { code: "LR", fr: "Libéria", en: "Liberia", cities: [] },
  { code: "LY", fr: "Libye", en: "Libya", cities: [] },
  { code: "LI", fr: "Liechtenstein", en: "Liechtenstein", cities: [] },
  { code: "LT", fr: "Lituanie", en: "Lithuania", cities: [] },
  { code: "LU", fr: "Luxembourg", en: "Luxembourg", cities: [] },
  { code: "MO", fr: "Macao", en: "Macao", cities: [] },
  { code: "MK", fr: "Macédoine du Nord", en: "North Macedonia", cities: [] },
  { code: "MG", fr: "Madagascar", en: "Madagascar", cities: [] },
  { code: "MY", fr: "Malaisie", en: "Malaysia", cities: [] },
  { code: "MW", fr: "Malawi", en: "Malawi", cities: [] },
  { code: "ML", fr: "Mali", en: "Mali", cities: [] },
  { code: "MT", fr: "Malte", en: "Malta", cities: [] },
  { code: "MA", fr: "Maroc", en: "Morocco", cities: [] },
  { code: "MQ", fr: "Martinique", en: "Martinique", cities: [] },
  { code: "MU", fr: "Maurice", en: "Mauritius", cities: [] },
  { code: "MR", fr: "Mauritanie", en: "Mauritania", cities: [] },
  { code: "YT", fr: "Mayotte", en: "Mayotte", cities: [] },
  { code: "MX", fr: "Mexique", en: "Mexico", cities: [] },
  { code: "FM", fr: "Micronésie", en: "Micronesia", cities: [] },
  { code: "MD", fr: "Moldavie", en: "Moldova", cities: [] },
  { code: "MC", fr: "Monaco", en: "Monaco", cities: [] },
  { code: "MN", fr: "Mongolie", en: "Mongolia", cities: [] },
  { code: "ME", fr: "Monténégro", en: "Montenegro", cities: [] },
  { code: "MS", fr: "Montserrat", en: "Montserrat", cities: [] },
  { code: "MZ", fr: "Mozambique", en: "Mozambique", cities: [] },
  { code: "MM", fr: "Myanmar", en: "Myanmar", cities: [] },
  { code: "NA", fr: "Namibie", en: "Namibia", cities: [] },
  { code: "NR", fr: "Nauru", en: "Nauru", cities: [] },
  { code: "NP", fr: "Népal", en: "Nepal", cities: [] },
  { code: "NI", fr: "Nicaragua", en: "Nicaragua", cities: [] },
  { code: "NE", fr: "Niger", en: "Niger", cities: [] },
  { code: "NG", fr: "Nigéria", en: "Nigeria", cities: [] },
  { code: "NU", fr: "Niue", en: "Niue", cities: [] },
  { code: "NO", fr: "Norvège", en: "Norway", cities: [] },
  { code: "NC", fr: "Nouvelle-Calédonie", en: "New Caledonia", cities: [] },
  { code: "NZ", fr: "Nouvelle-Zélande", en: "New Zealand", cities: [] },
  { code: "OM", fr: "Oman", en: "Oman", cities: [] },
  { code: "UG", fr: "Ouganda", en: "Uganda", cities: [] },
  { code: "UZ", fr: "Ouzbékistan", en: "Uzbekistan", cities: [] },
  { code: "PK", fr: "Pakistan", en: "Pakistan", cities: [] },
  { code: "PW", fr: "Palaos", en: "Palau", cities: [] },
  { code: "PS", fr: "Palestine", en: "Palestine", cities: [] },
  { code: "PA", fr: "Panama", en: "Panama", cities: [] },
  { code: "PG", fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea", cities: [] },
  { code: "PY", fr: "Paraguay", en: "Paraguay", cities: [] },
  { code: "NL", fr: "Pays-Bas", en: "Netherlands", cities: [] },
  { code: "PE", fr: "Pérou", en: "Peru", cities: [] },
  { code: "PH", fr: "Philippines", en: "Philippines", cities: [] },
  { code: "PL", fr: "Pologne", en: "Poland", cities: [] },
  { code: "PF", fr: "Polynésie française", en: "French Polynesia", cities: [] },
  { code: "PR", fr: "Porto Rico", en: "Puerto Rico", cities: [] },
  { code: "PT", fr: "Portugal", en: "Portugal", cities: [] },
  { code: "QA", fr: "Qatar", en: "Qatar", cities: [] },
  { code: "CF", fr: "République centrafricaine", en: "Central African Republic", cities: [] },
  { code: "DO", fr: "République dominicaine", en: "Dominican Republic", cities: [] },
  { code: "CZ", fr: "République tchèque", en: "Czech Republic", cities: [] },
  { code: "RE", fr: "La Réunion", en: "Réunion", cities: [] },
  { code: "RO", fr: "Roumanie", en: "Romania", cities: [] },
  { code: "GB", fr: "Royaume-Uni", en: "United Kingdom", cities: [] },
  { code: "RU", fr: "Russie", en: "Russia", cities: [] },
  { code: "RW", fr: "Rwanda", en: "Rwanda", cities: [] },
  { code: "EH", fr: "Sahara occidental", en: "Western Sahara", cities: [] },
  { code: "BL", fr: "Saint-Barthélemy", en: "Saint Barthélemy", cities: [] },
  { code: "KN", fr: "Saint-Christophe-et-Niévès", en: "Saint Kitts and Nevis", cities: [] },
  { code: "SM", fr: "Saint-Marin", en: "San Marino", cities: [] },
  { code: "MF", fr: "Saint-Martin", en: "Saint Martin", cities: [] },
  { code: "PM", fr: "Saint-Pierre-et-Miquelon", en: "Saint Pierre and Miquelon", cities: [] },
  { code: "VA", fr: "Vatican", en: "Vatican", cities: [] },
  { code: "VC", fr: "Saint-Vincent-et-les-Grenadines", en: "Saint Vincent and the Grenadines", cities: [] },
  { code: "SH", fr: "Sainte-Hélène", en: "Saint Helena", cities: [] },
  { code: "LC", fr: "Sainte-Lucie", en: "Saint Lucia", cities: [] },
  { code: "SB", fr: "Salomon", en: "Solomon Islands", cities: [] },
  { code: "WS", fr: "Samoa", en: "Samoa", cities: [] },
  { code: "AS", fr: "Samoa américaines", en: "American Samoa", cities: [] },
  { code: "ST", fr: "Sao Tomé-et-Principe", en: "Sao Tome and Principe", cities: [] },
  { code: "SN", fr: "Sénégal", en: "Senegal", cities: [] },
  { code: "RS", fr: "Serbie", en: "Serbia", cities: [] },
  { code: "SC", fr: "Seychelles", en: "Seychelles", cities: [] },
  { code: "SL", fr: "Sierra Leone", en: "Sierra Leone", cities: [] },
  { code: "SG", fr: "Singapour", en: "Singapore", cities: [] },
  { code: "SK", fr: "Slovaquie", en: "Slovakia", cities: [] },
  { code: "SI", fr: "Slovénie", en: "Slovenia", cities: [] },
  { code: "SO", fr: "Somalie", en: "Somalia", cities: [] },
  { code: "SD", fr: "Soudan", en: "Sudan", cities: [] },
  { code: "SS", fr: "Soudan du Sud", en: "South Sudan", cities: [] },
  { code: "LK", fr: "Sri Lanka", en: "Sri Lanka", cities: [] },
  { code: "SE", fr: "Suède", en: "Sweden", cities: [] },
  { code: "CH", fr: "Suisse", en: "Switzerland", cities: [] },
  { code: "SR", fr: "Suriname", en: "Suriname", cities: [] },
  { code: "SZ", fr: "Eswatini", en: "Eswatini", cities: [] },
  { code: "SY", fr: "Syrie", en: "Syria", cities: [] },
  { code: "TJ", fr: "Tadjikistan", en: "Tajikistan", cities: [] },
  { code: "TW", fr: "Taïwan", en: "Taiwan", cities: [] },
  { code: "TZ", fr: "Tanzanie", en: "Tanzania", cities: [] },
  { code: "TD", fr: "Tchad", en: "Chad", cities: [] },
  { code: "TH", fr: "Thaïlande", en: "Thailand", cities: [] },
  { code: "TL", fr: "Timor oriental", en: "Timor-Leste", cities: [] },
  { code: "TG", fr: "Togo", en: "Togo", cities: [] },
  { code: "TK", fr: "Tokelau", en: "Tokelau", cities: [] },
  { code: "TO", fr: "Tonga", en: "Tonga", cities: [] },
  { code: "TT", fr: "Trinité-et-Tobago", en: "Trinidad and Tobago", cities: [] },
  { code: "TN", fr: "Tunisie", en: "Tunisia", cities: [] },
  { code: "TM", fr: "Turkménistan", en: "Turkmenistan", cities: [] },
  { code: "TC", fr: "Îles Turques-et-Caïques", en: "Turks and Caicos Islands", cities: [] },
  { code: "TR", fr: "Turquie", en: "Turkey", cities: [] },
  { code: "TV", fr: "Tuvalu", en: "Tuvalu", cities: [] },
  { code: "UA", fr: "Ukraine", en: "Ukraine", cities: [] },
  { code: "UY", fr: "Uruguay", en: "Uruguay", cities: [] },
  { code: "VU", fr: "Vanuatu", en: "Vanuatu", cities: [] },
  { code: "VE", fr: "Venezuela", en: "Venezuela", cities: [] },
  { code: "VN", fr: "Vietnam", en: "Vietnam", cities: [] },
  { code: "WF", fr: "Wallis-et-Futuna", en: "Wallis and Futuna", cities: [] },
  { code: "YE", fr: "Yémen", en: "Yemen", cities: [] },
  { code: "ZM", fr: "Zambie", en: "Zambia", cities: [] },
  { code: "ZW", fr: "Zimbabwe", en: "Zimbabwe", cities: [] },
];

// Obtenir le nom du pays selon la langue
export function getCountryName(country: Country, lang: "FR" | "EN"): string {
  return lang === "FR" ? country.fr : country.en;
}

// Obtenir la liste triée par nom selon la langue
export function getSortedCountries(lang: "FR" | "EN"): Country[] {
  return [...COUNTRIES].sort((a, b) =>
    getCountryName(a, lang).localeCompare(getCountryName(b, lang), lang === "FR" ? "fr" : "en")
  );
}

// Obtenir les villes filtrées (legacy — retourne tableau vide, champ libre utilisé)
export function filterCities(_countryCode: string, _query: string): string[] {
  return [];
}
